//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCountry
    {
        public TblCountry()
        {
            this.TblStates = new HashSet<TblState>();
        }
    
        public int Country_Id { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<TblState> TblStates { get; set; }
    }
}
